openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/v1/images:
    post:
      tags:
      - images
      summary: Upload Image
      description: Upload and asynchronously process a new image file.
      operationId: upload_image_api_v1_images_post
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_image_api_v1_images_post'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - images
      summary: Read Images
      operationId: read_images_api_v1_images_get
      parameters:
      - name: skip
        in: query
        required: false
        schema:
          type: integer
          default: 0
          title: Skip
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 20
          title: Limit
      - name: sort_by
        in: query
        required: false
        schema:
          type: string
          default: upload_date
          title: Sort By
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
                title: Response Read Images Api V1 Images Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/images/{image_id}/favorite:
    post:
      tags:
      - images
      summary: Toggle Favorite
      description: Toggles the 'is_favorite' status of an image.
      operationId: toggle_favorite_api_v1_images__image_id__favorite_post
      parameters:
      - name: image_id
        in: path
        required: true
        schema:
          type: integer
          title: Image Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/images/{image_id}:
    delete:
      tags:
      - images
      summary: Delete Image
      operationId: delete_image_api_v1_images__image_id__delete
      parameters:
      - name: image_id
        in: path
        required: true
        schema:
          type: integer
          title: Image Id
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/albums/summary:
    get:
      tags:
      - albums
      summary: Get Album Summary
      description: Returns a summary of albums grouped by year and month.
      operationId: get_album_summary_api_v1_albums_summary_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  additionalProperties: true
                  type: object
                type: array
                title: Response Get Album Summary Api V1 Albums Summary Get
  /api/v1/albums/{year}/{month}:
    get:
      tags:
      - albums
      summary: Get Album Images
      description: Returns all images for a specific album (year and month).
      operationId: get_album_images_api_v1_albums__year___month__get
      parameters:
      - name: year
        in: path
        required: true
        schema:
          type: integer
          title: Year
      - name: month
        in: path
        required: true
        schema:
          type: integer
          title: Month
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
                title: Response Get Album Images Api V1 Albums  Year   Month  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/map/data:
    get:
      tags:
      - map
      summary: Get Map Data Json
      description: Returns a JSON list of all geotagged images with the data needed
        for the map.
      operationId: get_map_data_json_api_v1_map_data_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/stats:
    get:
      tags:
      - stats
      summary: Get Stats
      operationId: get_stats_api_v1_stats_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/suggestions/albums:
    get:
      tags:
      - suggestions
      summary: Get Album Suggestions
      description: Generate and return a list of AI-powered album suggestions.
      operationId: get_album_suggestions_api_v1_suggestions_albums_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Album Suggestions Api V1 Suggestions Albums Get
  /api/v1/filters/cameras:
    get:
      tags:
      - filters
      summary: Get Camera Filters
      description: Get a list of all unique camera models for filtering.
      operationId: get_camera_filters_api_v1_filters_cameras_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Camera Filters Api V1 Filters Cameras Get
  /api/v1/filters/locations:
    get:
      tags:
      - filters
      summary: Get Location Filters
      description: Get a list of all unique locations for filtering.
      operationId: get_location_filters_api_v1_filters_locations_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Location Filters Api V1 Filters Locations Get
  /api/v1/filters/dates:
    get:
      tags:
      - filters
      summary: Get Date Filters
      description: Get a list of all unique dates (year and month) for filtering.
      operationId: get_date_filters_api_v1_filters_dates_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Date Filters Api V1 Filters Dates Get
  /api/v1/search/ai:
    post:
      tags:
      - search
      summary: Ai Search Endpoint
      description: Performs a natural language search for images.
      operationId: ai_search_endpoint_api_v1_search_ai_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIQuery'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Image'
                type: array
                title: Response Ai Search Endpoint Api V1 Search Ai Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/config:
    get:
      summary: Get Config
      description: Returns the base API URL to the frontend.
      operationId: get_config_api_v1_config_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    AIQuery:
      properties:
        query:
          type: string
          title: Query
      type: object
      required:
      - query
      title: AIQuery
    AlbumBase:
      properties:
        name:
          type: string
          title: Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
      type: object
      required:
      - name
      title: AlbumBase
    Body_upload_image_api_v1_images_post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
      - file
      title: Body_upload_image_api_v1_images_post
    Image:
      properties:
        filename:
          type: string
          title: Filename
        filepath:
          type: string
          title: Filepath
        upload_date:
          type: string
          format: date-time
          title: Upload Date
        resolution:
          type: string
          title: Resolution
        image_size:
          type: integer
          title: Image Size
        mimetype:
          anyOf:
          - type: string
          - type: 'null'
          title: Mimetype
        id:
          type: integer
          title: Id
        details:
          anyOf:
          - $ref: '#/components/schemas/Metadata'
          - type: 'null'
        tags:
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          title: Tags
          default: []
        albums:
          items:
            $ref: '#/components/schemas/AlbumBase'
          type: array
          title: Albums
          default: []
        is_favorite:
          type: boolean
          title: Is Favorite
          default: false
        thumbnail_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Thumbnail Url
        medium_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Medium Url
        large_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Large Url
        status:
          type: string
          title: Status
          default: processing
      type: object
      required:
      - filename
      - filepath
      - upload_date
      - resolution
      - image_size
      - id
      title: Image
    Location:
      properties:
        latitude:
          type: number
          title: Latitude
        longitude:
          type: number
          title: Longitude
        address:
          anyOf:
          - type: string
          - type: 'null'
          title: Address
        id:
          type: integer
          title: Id
      type: object
      required:
      - latitude
      - longitude
      - id
      title: Location
    Metadata:
      properties:
        camera_model:
          anyOf:
          - type: string
          - type: 'null'
          title: Camera Model
        date_taken:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Date Taken
        f_number:
          anyOf:
          - type: number
          - type: 'null'
          title: F Number
        exposure_time:
          anyOf:
          - type: string
          - type: 'null'
          title: Exposure Time
        iso:
          anyOf:
          - type: integer
          - type: 'null'
          title: Iso
        focal_length:
          anyOf:
          - type: string
          - type: 'null'
          title: Focal Length
        lens_model:
          anyOf:
          - type: string
          - type: 'null'
          title: Lens Model
        raw_exif:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Raw Exif
        id:
          type: integer
          title: Id
        location:
          anyOf:
          - $ref: '#/components/schemas/Location'
          - type: 'null'
      type: object
      required:
      - id
      title: Metadata
    Tag:
      properties:
        name:
          type: string
          title: Name
        id:
          type: integer
          title: Id
      type: object
      required:
      - name
      - id
      title: Tag
